// Generated by Wrangler
// Run `wrangler types` to regenerate

import { Ai } from '@cloudflare/ai';

export interface Env {
	// AI Binding
	AI: Ai;

	// KV Namespace
	KV_BINDING: KVNamespace;

	// R2 Bucket
	PROJECT_FILES: R2Bucket;

	// Assets (for static files)
	ASSETS: Fetcher;
}

// Optional: Add more types if needed
export type ChatMessage = {
	role: 'system' | 'user' | 'assistant';
	content: string;
};